const mongoose = require('mongoose');

const bookingSchema = new mongoose.Schema({
  id: { type: Number, unique: true, index: true },
  property_id: { type: Number, index: true },
  guest_id: { type: Number, index: true },
  channel: { type: String, default: 'direct' },
  channel_booking_id: String,
  check_in: String,
  check_out: String,
  adults: { type: Number, default: 1 },
  children: { type: Number, default: 0 },
  infants: { type: Number, default: 0 },
  nightly_rate: { type: Number, default: 0 },
  subtotal: { type: Number, default: 0 },
  cleaning_fee: { type: Number, default: 0 },
  service_fee: { type: Number, default: 0 },
  taxes: { type: Number, default: 0 },
  gross_amount: { type: Number, default: 0 },
  commission_percent: { type: Number, default: 0 },
  commission_amount: { type: Number, default: 0 },
  net_amount: { type: Number, default: 0 },
  currency: { type: String, default: 'INR' },
  payment_status: { type: String, default: 'pending' },
  payment_method: String,
  paid_amount: { type: Number, default: 0 },
  pending_amount: { type: Number, default: 0 },
  booking_status: { type: String, default: 'confirmed' },
  guest_message: String,
  special_requests: String,
  check_in_time: { type: String, default: '2:00 PM' },
  check_out_time: { type: String, default: '11:00 AM' },
  actual_check_in: String,
  actual_check_out: String,
  confirmed_at: String,
  cancelled_at: String,
  cancellation_reason: String,
}, { timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' } });

module.exports = mongoose.model('Booking', bookingSchema);
